source.go
Moving commit from Conduit to the SDK: https://github.com/ConduitIO/conduit/pull/230/commits/f8d99d9367473244325b624dfbf7ed9a35427787
This change makes sure that the context passed to `Open` will be closed once `Stop` is called. This is useful because `Open` might be used to spawn background jobs that need to be notified when the plugin should stop. Otherwise the user would need to detect it in the `Read` function.
=> Close context in Source.Open when plugin stops

acceptance_testing.go
This PR changes how records are generated and how they are compared. By default, the driver generates records with both structured and raw data in fields `Key` and `Payload`, possibly even mixed in the same record. This behavior can be configured through `ConfigurableAcceptanceTestDriverConfig.GenerateDataType` so the caller can choose if they want the test to generate only raw or structured data. The record comparison was relaxed so that the fields `Key` and `Payload` are treated as equal if they contain different data types (e.g. raw and structured data) and both data types are converted to the same byte slice using the function `Data.Bytes()`.
Additionally, the field `CreatedAt` of the actual record is now enforced to be equal or after the `CreatedAt` value of the expected record, …
=> Acceptance tests: Generate structured data

source.go, source_test.go
This changes the semantics of a graceful source stop. The source now returns the information about the last record position, Conduit can now determine when it received all records and safely stop the stream. This PR also adds tests for the source `Run` function.
Second half of https://github.com/ConduitIO/conduit-connector-sdk/pull/22, fixes https://github.com/ConduitIO/conduit/issues/391 and fixes https://github.com/ConduitIO/conduit/issues/392.
update/change.
=> Source stop semantics

specifier.go, specifier_test.go
Fixes nil pointer in one-sided connectors (only a source / destination).
Fixes https://github.com/ConduitIO/conduit/issues/587.
update/change.
=> Fix nil pointer in one-sided connectors

cmd/paramgen/README.md
paramgen readme had the wrong instructions of how to install it
update/change.
=> fix paramgen installation command in readme

destination.go, source.go, validation.go, validation_test.go
The fix is returning an updated map of Config that has the default values, and using that map when calling `impl.Configure()`
Fixes #50 
update/change.
=> fix unpopulated default values bug

acceptance_testing.go
Two changes:
- Allow the version string `(devel)` in addition to semantic versions (for connectors that inject the version via `-ldflags`)
- Detect required parameters based on validation `ValidationRequired`.
update/change.
=> Acceptance test improvements

destination_middleware_test.go, record_formatter.go, record_formatter_test.go
This PR makes sure that records that contain actual raw data can be converted to debezium records by hoisting the raw data into a field. By default that field is named `opencdc.rawData` but it can be changed by setting `debezium.rawData.key`.
update/change.
=> Debezium raw data

cmd/paramgen/internal/paramgen.go, cmd/paramgen/internal/paramgen_test.go
This fixes a mismatch between `paramgen` and `sdk.Util.ParseConfig`, where `ParseConfig` did not expect that embedded structs without a name would have a prefix (see [this test case](https://github.com/ConduitIO/conduit-connector-sdk/blob/29058268e9933edc3f99fcb62f01015a4c778fbd/util_test.go#L57)). Now `paramgen` also does not add that prefix to generated parameters.
update/change.
=> Paramgen: don't add prefix if nested field is not named

destination.go, destination_test.go, go.mod, go.sum, mock_destination_test.go, mock_source_test.go, source.go, source_test.go, unimplemented.go
This PR is the follow-up to https://github.com/ConduitIO/conduit-connector-protocol/pull/22, where connector lifecycle events were added to the connector protocol. In this PR we expose those methods to connectors so they can react to those events.
Fixes https://github.com/ConduitIO/conduit/issues/936.
update/change.
=> Lifecycle event methods

source.go
Since #77 we cancel the Open and Read contexts in Teardown. However, the context cancellation functions may not have been set (e.g. when creating connectors through the API/UI, a connector configuration is validated by calling `Configure` and then `Teardown`).  
update/change.
=> Check for open and read in teardown

destination.go, destination_middleware.go, internal/batcher.go, internal/batcher_test.go, kafkaconnect/reflect.go, source.go
Implements record batching in destinations. Batching can be turned on using the connector config options `sdk.batch.size` and `sdk.batch.delay`, e.g.:
```
sdk.batch.size: 10000 # trigger batch when 10000 records are collected
sdk.batch.delay: 2s   # trigger batch after 2 seconds even if it didn't reach the full size
```
Fixes #74 
update/change.
=> Destination record batching

cmd/paramgen/internal/paramgen.go, cmd/paramgen/internal/testdata/complex/tools.go
A naive check to ignore files containing the comment `//go:build tools`, which are commonly found in Conduit connectors and can cause issues with paramgen.
update/change.
=> Ignore files marked with go:build tools

util.go
When parsing configs using `sdk.Util.ParseConfig`, the configuration parameters used need to be provided through `NewSource()`/`NewDestination()` so that they include the SDK middleware parameters too.
update/change.
=> Add note about params used when parsing configs

destination_middleware.go, destination_middleware_test.go, source_middleware.go, source_middleware_test.go
This PR adds `DestinationWithSchemaExtraction` middleware, which is the counterpart to `SourceWithSchemaExtraction` introduced in https://github.com/ConduitIO/conduit-connector-sdk/pull/152. It checks the record metadata for an attached schema subject and version, fetches the schema and decodes the raw payload into a structured one using the obtained schema.
A few additional changes:
- Functions `DestinationWithMiddleware` and `SourceWithMiddleware` now apply middleware in the reverse order, so the order of calls between the middleware is in the same order as supplied by the caller.
- Parameters that end with `*.enable` changed to `*.enabled`.
- Rename a few tests.
Fixes #138
update/change.
=> Destination middleware for decoding data with attached schema

schema/in_memory.go, schema/in_memory_test.go
We added IDs to schemas in a later change and forgot to update the in-memory schema service to generate IDs.
update/change.
=> Generate IDs in in-memory schema service

source_middleware.go, source_middleware_test.go
Prepend the record metadata value of `opencdc.collection` to the schema subject, if it exists, otherwise the functionality stays the same. This ensures that we keep schemas separate for each collection.
update/change.
=> Prepend collection name to subject

.golangci.yml, destination_middleware_test.go, go.mod, go.sum, schema/cached.go, schema/cached_test.go, schema/schema.go, source_middleware.go, source_middleware_test.go
This PR contains two additions to schemas:
- Allows the connector to return a record with structured data and an attached schema. This means the connector doesn't have to take care of encoding the data, it can only provide the schema and the middleware will use the schema to encode the data.
- The use case are DB connectors like Postgres, which can do a better job extracting the schema directly from the DB. Those can simply attach the extracted schema to the record and return structured data as always, the middleware will take care of the encoding.
- Adds caches around the standalone schema service.
- Note that the in-memory schema service is also cached, as it would otherwise not reflect the correct behavior, it's not smart enough to detect the same schema and will always increment the …
=> Allow provided schema, schema cache

destination_middleware.go, source_middleware.go
Suggestion to simplify middleware options. Now you can supply the config itself as an option, instead of having to specify the `Apply` method.
=> Simplify middleware options

.github/pull_request_template.md, logger.go, serve.go
Try to get the log level from an env variable and apply it to the standalone logger.
update/change.
=> Set log level in connectors

destination_middleware.go, destination_middleware_test.go
The rate limit was currently applied _per write_ and not _per record_. I think it makes more sense if we apply it per record, it's easier to reason about and configure.
=> Apply rate limit per record

specifier.go, specifier_test.go
Specification was coming empty when plugins were described.
Looks like params were not assigned to the spec when it was created.
=> Assign source and dst params to spec

.golangci.yml, destination_middleware.go, destination_middleware_test.go, schema/cached.go, schema/cached_test.go, schema/commons.go, schema/in_memory.go, schema/in_memory_test.go, schema/schema.go, source_middleware.go, source_middleware_test.go
This should make it easier to use the `schema` package, since you have everything there and don't need to import `conduit-commons/schema` directly.
=> Add aliases for types in schema package

source_middleware.go, source_middleware_test.go
Fixes https://github.com/ConduitIO/conduit-connector-sdk/issues/197.
Previously, encoding a record's data was tied to the flag enabling schema extraction. This PR makes sure that encoding happens whenever there's a schema available and the data is structured. Since extraction and encoding are separate actions, the middleware has also been split.
=> Encode key and payload whenever a schema is available

acceptance_testing.go
We introduced dynamic configuration parameters (https://github.com/ConduitIO/conduit-commons/pull/35) that allow wildcards in parameter names. This PR changes one of the acceptance tests to allow the wildcard in a parameter name.
=> Allow wildcard in param name

specgen/specgen/model/v1/model.go, specgen/specgen/model/v1/model_test.go, specgen/specgen/tests/parse_specs/tags/want.yaml, specgen/specgen/traverse.go
=>  specgen: Order fields (required first, then by name alphabetically)

source_middleware.go, source_middleware_test.go
sourceWithEncoding works not propertly in combination with sourceWithBatch middleware.
sourcePluginAdapter in runRead method first tries to call ReadN method and if it fails with Unimplemented error, it fallbacks on Read method.
If Source implementation supports ReadN method, this method will be called instead of Read and the result will not be encoded propertly.
If Source doesn't implement ReadN method, but supports batches using sourceWithBatch middleware the result is the same: records are not encoded.
Fixes # (issue)
=> sourceWithEncoding middleware works impropertly in combination with sourceWithBatch

conn-sdk-cli/main.go, conn-sdk-cli/specgen/cmd.go
1. Currently, conn-sdk-cli uses `html/template` which means that the program to extract the specification uses the following import `pkg_ &#34;github.com/conduitio/conduit-connector-postgres&#34;`, which breaks the program.
2. A flag name was wrong, which caused a nil pointer dereference panic.
=> conn-sdk-cli: use text/template, fix flag name

serve.go
Adds the ability to get the specs in the CLI from a standalone connector. You can use `spec`, `specs`, `specification` or `specifications` to print the `connector.yaml` stored in the connector.
<details>
<summary>Example output of the postgres connector</summary>
```
$ ./conduit-connector-postgres specs
version: "1.0"
specification:
name: postgres
summary: A PostgreSQL source and destination plugin for Conduit.
description: ""
version: v0.10.1-34-g179ac45-dirty
author: Meroxa, Inc.
source:
parameters:
- name: url
description: URL is the connection string for the Postgres database.
type: string
default: ""
validations:
- type: required
value: ""
- name: cdcMode
description: CDCMode determines how the connector should listen to changes.
type: string
default: auto
validations:
- type: …
```
=> Add specs and version command

conn-sdk-cli/readmegen/generate_test.go, conn-sdk-cli/readmegen/preprocess.go
A description is normally a multiline markdown document. Even more - I'll argue that it will most of the time start with a chapter (e.g. `## Source` or similar). For this to work, the line can't start with a HTML comment, so we add a new line in front to push the description start into a new line.
=> Add new line before description

destination_middleware.go, destination_middleware_test.go, destination_test.go, source_middleware.go, source_middleware_test.go
Middleware wrapping wasn't properly done if the middleware config was nested deeper than in the 1st level (which is the case for default middleware).
=> Fix middleware wrapping

conn-sdk-cli/specgen/testdata/custom_embedded_struct/want.yaml, conn-sdk-cli/specgen/testdata/custom_middleware_config/want.yaml, conn-sdk-cli/specgen/testdata/param_sorting/want.yaml, source_middleware.go
Duration validations are not supported by conduit-common (https://github.com/ConduitIO/conduit-commons/issues/169)
This bug (?) doesn't allow to use batching.
There is no such validation in DestinationWithBatch and looks like this validation is pretty useless.
=> disable batch delay validations on SourceWithBatch middleware

source_middleware.go
This PR fixes the issue described in the next paragraph.
When I was running a custom Conduit app:
* with a few additional built-in plugins
* a Mongo-to-Kafka pipeline
* and the new pipeline architecture enabled
I got the following error:
```
2025-02-28T08:33:57+00:00 DBG calling Teardown component=builtin.sourcePluginAdapter connector_id=mongo-to-kafka:mongo-source plugin_name=builtin:mongo plugin_type=source request={} request_id=0e13942c-ffe2-4c94-b342-2c44bec767ff
panic: send on closed channel
goroutine 174 [running]:
github.com/conduitio/conduit-connector-sdk.(*sourceWithBatch).runRead(0xc000a8ff40, {0x321b730, 0xc0008e2af0})
/go/pkg/mod/github.com/conduitio/conduit-connector-sdk@v0.13.1/source_middleware.go:777 +0x453
created by …
```
=> Fix issue with closing channel in SourceWithBatch

record_serializer.go, record_serializer_test.go
This PR fixes #216 by adding the `missingkey=error` option to the template configuration. This ensures that template execution fails when encountering missing keys instead of silently writing the entire record.
- Added `missingkey=error` to template configuration
- Improved error messages for template parsing and execution
- Added comprehensive test cases for missing key scenarios
=> fix: fail on missing template keys

conn-sdk-cli/readmegen/preprocess.go, conn-sdk-cli/readmegen/templates/parameters.yaml.tmpl, conn-sdk-cli/readmegen/testdata/test1want.md
Add the connector type to the generated yaml parameters.
Fixes #301
=> Include type when generating yaml parameters
