ConduitIO/conduit-connector-sdk

destination.go

Changes logic to be more intuitive, now the SDK makes sure that `Stop` will wait for `Run` to return before it exits. It will wait for at most 1 minute. This logic was previously in `Teardown` but it makes more sense to wait for run to stop before any remaining records are flushed, otherwise more records might still come in.
This was discovered while working on https://github.com/ConduitIO/conduit/issues/259.
Tests are missing, although it was tested manually with Conduit integration tests and the file connector.

Wait for acks in destination stop

---

README.md

Readme FAQ

---

acceptance_testing.go

This PR allows the acceptance test driver to define the read/write timeout. The default 5 second timeout can be an issue for some sources.
Fixes https://github.com/ConduitIO/conduit-connector-sdk/issues/23.
Depends on https://github.com/ConduitIO/conduit-connector-sdk/pull/21
update/change.

Acceptance tests: Configurable read/write timeout

---

acceptance_testing.go

Use driver read timeout

---

.github/workflows/lint.yml
go.mod
go.sum
util.go
util_test.go

Related to #(https://github.com/ConduitIO/conduit/issues/696)
update/change.

add ParseConfig function under Util

---

validation.go
validation_test.go

Fixes the bug where optional parameters are still validated when empty.
update/change.

Ignore validations for optional parameters

---

.github/workflows/lint.yml
destination.go
internal/atomicvaluewatcher.go
source.go
specifier.go

Upgrade linter, add timeout

---

source.go
source_test.go

This change ensures the following:
- When `Teardown` is called without `Stop`, the context in `Open` and `Read` will still get cancelled. This could happen when the shutdown is not graceful, but rather it was triggered because an error happened in Conduit. In that case Conduit calls `Teardown` directly without draining records.
- If the connector gets stuck and not responding to a stopped context (i.e. keeps on reading records or waiting for new records) the SDK is now able to detach from it. In `Stop` it will wait 1 minute for the connector to stop reading new records, and another 1 minute in `Teardown`. After that it kills the tomb which stops the stream forcefully.
**Important** - even though this should add better resilience to recover from stuck connectors, the timeouts should be …

Allow SDK to detach from stuck connectors

---

destination.go
error.go
unimplemented.go

This PR improves error messages.
update/change.

Improve error messages for action not implemented

---

acceptance_testing.go

This PR adds the ability to set a custom context in acceptance tests. It also changes the default context to include a zerolog logger that logs to test output.
update/change.

Allow setting custom context in acceptance tests

---

README.md

Adds "enable logging" FAQ.
update/change.

Add enable logging FAQ

---

cmd/paramgen/internal/paramgen.go

Include package names in error

---

go.mod
go.sum

Upgrade conduit-commons to v0.2.0

---

destination.go
destination_middleware.go
destination_middleware_test.go
destination_test.go

As mentioned in https://github.com/ConduitIO/conduit-connector-sdk/pull/152#discussion_r1684477189, this PR adds destination middleware options to match the source middleware options introduced in that PR.
update/change.

Destination middleware options

---

acceptance_testing.go

We introduced of a [global serde cache](https://github.com/ConduitIO/conduit-commons/blob/81748fb51964f4aff6c56fb88df5bd0e9ec24c24/schema/schema.go#L100-L103) in conduit-commons, which spawns a goroutine that is taking care of cleaning the cache in the background. We need to ignore the known goroutine in acceptance test verifications of goroutine leaks.
update/change.

Add default goleak option

---

go.mod
go.sum
schema/schema.go
serve.go

Follow up of https://github.com/ConduitIO/conduit-connector-protocol/pull/119

chore: consolidate environment variables

---

destination_middleware.go

Forgot to remove the destination middleware cache in https://github.com/ConduitIO/conduit-connector-sdk/pull/162, it's not needed anymore because we have a cache on the level of the schema service.

Remove the destination middleware cache

---

go.mod
go.sum

Upgrade conduit-connector-protocol to v0.7.0

---

util.go
util_test.go

Please include a summary of the change and what type of change it is (new feature, bug fix, refactoring, documentation).
Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

Override version from connector.yaml

---

go.mod
go.sum
serve.go

Depends on https://github.com/ConduitIO/conduit-connector-protocol/pull/213
Part of https://github.com/ConduitIO/conduit/issues/547

feat: Add ability to configure record size
